using System.Collections.Frozen;
using System.Diagnostics.CodeAnalysis;

namespace EInvoiceSender.Core.Validation;

/// <summary>
/// Laenderkennungen nach ISO 3166-1 alpha-2 (BT-40 / BT-55). Reine
/// Nachschlagetabelle ohne Geschaeftslogik. Anders als bei den uebrigen
/// Codelisten dieses Namensraums ist diese Liste bewusst
/// <b>vollstaendig</b>: alle aktuell offiziell zugewiesenen
/// ISO-3166-1-alpha-2-Codes (rund 249 Stueck), alphabetisch nach Code
/// sortiert. Zurueckgezogene Codes (z. B. <c>AN</c>, <c>CS</c>, <c>TP</c>,
/// <c>ZR</c>) und nicht offiziell zugewiesene Codes (z. B. <c>XK</c> fuer
/// den Kosovo, der nur als Uebergangscode einzelner Organisationen
/// verwendet wird) sind absichtlich nicht enthalten.
/// </summary>
public static class CountryCodeList
{
    private static readonly FrozenDictionary<string, string> Names = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["AD"] = "Andorra",
        ["AE"] = "Vereinigte Arabische Emirate",
        ["AF"] = "Afghanistan",
        ["AG"] = "Antigua und Barbuda",
        ["AI"] = "Anguilla",
        ["AL"] = "Albanien",
        ["AM"] = "Armenien",
        ["AO"] = "Angola",
        ["AQ"] = "Antarktis",
        ["AR"] = "Argentinien",
        ["AS"] = "Amerikanisch-Samoa",
        ["AT"] = "Oesterreich",
        ["AU"] = "Australien",
        ["AW"] = "Aruba",
        ["AX"] = "Aalandinseln",
        ["AZ"] = "Aserbaidschan",
        ["BA"] = "Bosnien und Herzegowina",
        ["BB"] = "Barbados",
        ["BD"] = "Bangladesch",
        ["BE"] = "Belgien",
        ["BF"] = "Burkina Faso",
        ["BG"] = "Bulgarien",
        ["BH"] = "Bahrain",
        ["BI"] = "Burundi",
        ["BJ"] = "Benin",
        ["BL"] = "Saint-Barthelemy",
        ["BM"] = "Bermuda",
        ["BN"] = "Brunei Darussalam",
        ["BO"] = "Bolivien",
        ["BQ"] = "Bonaire, Sint Eustatius und Saba",
        ["BR"] = "Brasilien",
        ["BS"] = "Bahamas",
        ["BT"] = "Bhutan",
        ["BV"] = "Bouvetinsel",
        ["BW"] = "Botsuana",
        ["BY"] = "Belarus",
        ["BZ"] = "Belize",
        ["CA"] = "Kanada",
        ["CC"] = "Kokosinseln",
        ["CD"] = "Kongo, Demokratische Republik",
        ["CF"] = "Zentralafrikanische Republik",
        ["CG"] = "Kongo",
        ["CH"] = "Schweiz",
        ["CI"] = "Cote d'Ivoire",
        ["CK"] = "Cookinseln",
        ["CL"] = "Chile",
        ["CM"] = "Kamerun",
        ["CN"] = "China",
        ["CO"] = "Kolumbien",
        ["CR"] = "Costa Rica",
        ["CU"] = "Kuba",
        ["CV"] = "Cabo Verde",
        ["CW"] = "Curacao",
        ["CX"] = "Weihnachtsinsel",
        ["CY"] = "Zypern",
        ["CZ"] = "Tschechien",
        ["DE"] = "Deutschland",
        ["DJ"] = "Dschibuti",
        ["DK"] = "Daenemark",
        ["DM"] = "Dominica",
        ["DO"] = "Dominikanische Republik",
        ["DZ"] = "Algerien",
        ["EC"] = "Ecuador",
        ["EE"] = "Estland",
        ["EG"] = "Aegypten",
        ["EH"] = "Westsahara",
        ["ER"] = "Eritrea",
        ["ES"] = "Spanien",
        ["ET"] = "Aethiopien",
        ["FI"] = "Finnland",
        ["FJ"] = "Fidschi",
        ["FK"] = "Falklandinseln",
        ["FM"] = "Mikronesien",
        ["FO"] = "Faeroeer",
        ["FR"] = "Frankreich",
        ["GA"] = "Gabun",
        ["GB"] = "Vereinigtes Koenigreich",
        ["GD"] = "Grenada",
        ["GE"] = "Georgien",
        ["GF"] = "Franzoesisch-Guayana",
        ["GG"] = "Guernsey",
        ["GH"] = "Ghana",
        ["GI"] = "Gibraltar",
        ["GL"] = "Groenland",
        ["GM"] = "Gambia",
        ["GN"] = "Guinea",
        ["GP"] = "Guadeloupe",
        ["GQ"] = "Aequatorialguinea",
        ["GR"] = "Griechenland",
        ["GS"] = "Suedgeorgien und die Suedlichen Sandwichinseln",
        ["GT"] = "Guatemala",
        ["GU"] = "Guam",
        ["GW"] = "Guinea-Bissau",
        ["GY"] = "Guyana",
        ["HK"] = "Hongkong",
        ["HM"] = "Heard- und McDonald-Inseln",
        ["HN"] = "Honduras",
        ["HR"] = "Kroatien",
        ["HT"] = "Haiti",
        ["HU"] = "Ungarn",
        ["ID"] = "Indonesien",
        ["IE"] = "Irland",
        ["IL"] = "Israel",
        ["IM"] = "Insel Man",
        ["IN"] = "Indien",
        ["IO"] = "Britisches Territorium im Indischen Ozean",
        ["IQ"] = "Irak",
        ["IR"] = "Iran",
        ["IS"] = "Island",
        ["IT"] = "Italien",
        ["JE"] = "Jersey",
        ["JM"] = "Jamaika",
        ["JO"] = "Jordanien",
        ["JP"] = "Japan",
        ["KE"] = "Kenia",
        ["KG"] = "Kirgisistan",
        ["KH"] = "Kambodscha",
        ["KI"] = "Kiribati",
        ["KM"] = "Komoren",
        ["KN"] = "St. Kitts und Nevis",
        ["KP"] = "Nordkorea",
        ["KR"] = "Suedkorea",
        ["KW"] = "Kuwait",
        ["KY"] = "Kaimaninseln",
        ["KZ"] = "Kasachstan",
        ["LA"] = "Laos",
        ["LB"] = "Libanon",
        ["LC"] = "St. Lucia",
        ["LI"] = "Liechtenstein",
        ["LK"] = "Sri Lanka",
        ["LR"] = "Liberia",
        ["LS"] = "Lesotho",
        ["LT"] = "Litauen",
        ["LU"] = "Luxemburg",
        ["LV"] = "Lettland",
        ["LY"] = "Libyen",
        ["MA"] = "Marokko",
        ["MC"] = "Monaco",
        ["MD"] = "Republik Moldau",
        ["ME"] = "Montenegro",
        ["MF"] = "Saint-Martin (franzoesischer Teil)",
        ["MG"] = "Madagaskar",
        ["MH"] = "Marshallinseln",
        ["MK"] = "Nordmazedonien",
        ["ML"] = "Mali",
        ["MM"] = "Myanmar",
        ["MN"] = "Mongolei",
        ["MO"] = "Macau",
        ["MP"] = "Noerdliche Marianen",
        ["MQ"] = "Martinique",
        ["MR"] = "Mauretanien",
        ["MS"] = "Montserrat",
        ["MT"] = "Malta",
        ["MU"] = "Mauritius",
        ["MV"] = "Malediven",
        ["MW"] = "Malawi",
        ["MX"] = "Mexiko",
        ["MY"] = "Malaysia",
        ["MZ"] = "Mosambik",
        ["NA"] = "Namibia",
        ["NC"] = "Neukaledonien",
        ["NE"] = "Niger",
        ["NF"] = "Norfolkinsel",
        ["NG"] = "Nigeria",
        ["NI"] = "Nicaragua",
        ["NL"] = "Niederlande",
        ["NO"] = "Norwegen",
        ["NP"] = "Nepal",
        ["NR"] = "Nauru",
        ["NU"] = "Niue",
        ["NZ"] = "Neuseeland",
        ["OM"] = "Oman",
        ["PA"] = "Panama",
        ["PE"] = "Peru",
        ["PF"] = "Franzoesisch-Polynesien",
        ["PG"] = "Papua-Neuguinea",
        ["PH"] = "Philippinen",
        ["PK"] = "Pakistan",
        ["PL"] = "Polen",
        ["PM"] = "Saint-Pierre und Miquelon",
        ["PN"] = "Pitcairninseln",
        ["PR"] = "Puerto Rico",
        ["PS"] = "Staat Palaestina",
        ["PT"] = "Portugal",
        ["PW"] = "Palau",
        ["PY"] = "Paraguay",
        ["QA"] = "Katar",
        ["RE"] = "Reunion",
        ["RO"] = "Rumaenien",
        ["RS"] = "Serbien",
        ["RU"] = "Russische Foederation",
        ["RW"] = "Ruanda",
        ["SA"] = "Saudi-Arabien",
        ["SB"] = "Salomonen",
        ["SC"] = "Seychellen",
        ["SD"] = "Sudan",
        ["SE"] = "Schweden",
        ["SG"] = "Singapur",
        ["SH"] = "St. Helena, Ascension und Tristan da Cunha",
        ["SI"] = "Slowenien",
        ["SJ"] = "Svalbard und Jan Mayen",
        ["SK"] = "Slowakei",
        ["SL"] = "Sierra Leone",
        ["SM"] = "San Marino",
        ["SN"] = "Senegal",
        ["SO"] = "Somalia",
        ["SR"] = "Suriname",
        ["SS"] = "Suedsudan",
        ["ST"] = "Sao Tome und Principe",
        ["SV"] = "El Salvador",
        ["SX"] = "Sint Maarten (niederlaendischer Teil)",
        ["SY"] = "Syrien",
        ["SZ"] = "Eswatini",
        ["TC"] = "Turks- und Caicosinseln",
        ["TD"] = "Tschad",
        ["TF"] = "Franzoesische Sued- und Antarktisgebiete",
        ["TG"] = "Togo",
        ["TH"] = "Thailand",
        ["TJ"] = "Tadschikistan",
        ["TK"] = "Tokelau",
        ["TL"] = "Timor-Leste",
        ["TM"] = "Turkmenistan",
        ["TN"] = "Tunesien",
        ["TO"] = "Tonga",
        ["TR"] = "Tuerkei",
        ["TT"] = "Trinidad und Tobago",
        ["TV"] = "Tuvalu",
        ["TW"] = "Taiwan",
        ["TZ"] = "Tansania",
        ["UA"] = "Ukraine",
        ["UG"] = "Uganda",
        ["UM"] = "Amerikanisch-Ozeanien (United States Minor Outlying Islands)",
        ["US"] = "Vereinigte Staaten",
        ["UY"] = "Uruguay",
        ["UZ"] = "Usbekistan",
        ["VA"] = "Vatikanstadt",
        ["VC"] = "St. Vincent und die Grenadinen",
        ["VE"] = "Venezuela",
        ["VG"] = "Britische Jungferninseln",
        ["VI"] = "Amerikanische Jungferninseln",
        ["VN"] = "Vietnam",
        ["VU"] = "Vanuatu",
        ["WF"] = "Wallis und Futuna",
        ["WS"] = "Samoa",
        ["YE"] = "Jemen",
        ["YT"] = "Mayotte",
        ["ZA"] = "Suedafrika",
        ["ZM"] = "Sambia",
        ["ZW"] = "Simbabwe",
    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Alle Laender als Auswahlliste, nach dem deutschen Namen sortiert.
    /// Fuer die Auswahlfelder der Oberflaeche.
    /// </summary>
    public static IReadOnlyList<(string Code, string Name)> All { get; } =
        [.. Names.Select(e => (Code: e.Key.ToUpperInvariant(), Name: e.Value))
                 .OrderBy(e => e.Name, StringComparer.CurrentCulture)];

    /// <summary>
    /// Prueft, ob <paramref name="code"/> ein offiziell zugewiesener
    /// ISO-3166-1-alpha-2-Code ist. Gross-/Kleinschreibung und umgebende
    /// Leerzeichen spielen keine Rolle. Liefert <see langword="false"/> bei
    /// <see langword="null"/>, leerem oder reinem Leerraum-Text – wirft nie.
    /// </summary>
    public static bool IsValid(string? code)
    {
        if (string.IsNullOrWhiteSpace(code))
        {
            return false;
        }

        return Names.ContainsKey(code.Trim());
    }

    /// <summary>
    /// Liefert den deutschen Namen des Landes zu einem gueltigen Code.
    /// </summary>
    public static bool TryGetName(string? code, [MaybeNullWhen(false)] out string germanName)
    {
        if (string.IsNullOrWhiteSpace(code))
        {
            germanName = null;
            return false;
        }

        return Names.TryGetValue(code.Trim(), out germanName);
    }
}
